# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nexus.protos.tts import tts_pb2 as nexus_dot_protos_dot_tts_dot_tts__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus/protos/tts/tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TtsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
                '/qwen_tts.service.v1.TtsService/Synthesize',
                request_serializer=nexus_dot_protos_dot_tts_dot_tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.DuplexSynthesize = channel.stream_stream(
                '/qwen_tts.service.v1.TtsService/DuplexSynthesize',
                request_serializer=nexus_dot_protos_dot_tts_dot_tts__pb2.DuplexSynthesizeRequest.SerializeToString,
                response_deserializer=nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.FromString,
                _registered_method=True)


class TtsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DuplexSynthesize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=nexus_dot_protos_dot_tts_dot_tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.SerializeToString,
            ),
            'DuplexSynthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.DuplexSynthesize,
                    request_deserializer=nexus_dot_protos_dot_tts_dot_tts__pb2.DuplexSynthesizeRequest.FromString,
                    response_serializer=nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qwen_tts.service.v1.TtsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qwen_tts.service.v1.TtsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TtsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qwen_tts.service.v1.TtsService/Synthesize',
            nexus_dot_protos_dot_tts_dot_tts__pb2.SynthesizeRequest.SerializeToString,
            nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DuplexSynthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/qwen_tts.service.v1.TtsService/DuplexSynthesize',
            nexus_dot_protos_dot_tts_dot_tts__pb2.DuplexSynthesizeRequest.SerializeToString,
            nexus_dot_protos_dot_tts_dot_tts__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
