# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus/protos/tts/tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nexus/protos/tts/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anexus/protos/tts/tts.proto\x12\x13qwen_tts.service.v1\"J\n\x0eReferenceVoice\x12\x11\n\tpcm_s16le\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08ref_text\x18\x03 \x01(\t\"r\n\x0bVoiceSource\x12>\n\x0freference_voice\x18\x01 \x01(\x0b\x32#.qwen_tts.service.v1.ReferenceVoiceH\x00\x12\x19\n\x0fpreset_voice_id\x18\x02 \x01(\tH\x00\x42\x08\n\x06source\"\x80\x01\n\x11SynthesizeRequest\x12/\n\x05voice\x18\x01 \x01(\x0b\x32 .qwen_tts.service.v1.VoiceSource\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x1a\n\x12\x64\x65\x63oder_chunk_size\x18\x04 \x01(\x05\"s\n\x12\x44uplexStreamConfig\x12/\n\x05voice\x18\x01 \x01(\x0b\x32 .qwen_tts.service.v1.VoiceSource\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x1a\n\x12\x64\x65\x63oder_chunk_size\x18\x03 \x01(\x05\"u\n\x17\x44uplexSynthesizeRequest\x12\x39\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\'.qwen_tts.service.v1.DuplexStreamConfigH\x00\x12\x14\n\ntext_chunk\x18\x02 \x01(\tH\x00\x42\t\n\x07payload\"I\n\nAudioChunk\x12\x11\n\tpcm_s16le\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\r2\xcc\x01\n\nTtsService\x12W\n\nSynthesize\x12&.qwen_tts.service.v1.SynthesizeRequest\x1a\x1f.qwen_tts.service.v1.AudioChunk0\x01\x12\x65\n\x10\x44uplexSynthesize\x12,.qwen_tts.service.v1.DuplexSynthesizeRequest\x1a\x1f.qwen_tts.service.v1.AudioChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus.protos.tts.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFERENCEVOICE']._serialized_start=51
  _globals['_REFERENCEVOICE']._serialized_end=125
  _globals['_VOICESOURCE']._serialized_start=127
  _globals['_VOICESOURCE']._serialized_end=241
  _globals['_SYNTHESIZEREQUEST']._serialized_start=244
  _globals['_SYNTHESIZEREQUEST']._serialized_end=372
  _globals['_DUPLEXSTREAMCONFIG']._serialized_start=374
  _globals['_DUPLEXSTREAMCONFIG']._serialized_end=489
  _globals['_DUPLEXSYNTHESIZEREQUEST']._serialized_start=491
  _globals['_DUPLEXSYNTHESIZEREQUEST']._serialized_end=608
  _globals['_AUDIOCHUNK']._serialized_start=610
  _globals['_AUDIOCHUNK']._serialized_end=683
  _globals['_TTSSERVICE']._serialized_start=686
  _globals['_TTSSERVICE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
