"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReferenceVoice(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PCM_S16LE_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    REF_TEXT_FIELD_NUMBER: _builtins.int
    pcm_s16le: _builtins.bytes
    sample_rate: _builtins.int
    ref_text: _builtins.str
    def __init__(
        self,
        *,
        pcm_s16le: _builtins.bytes = ...,
        sample_rate: _builtins.int = ...,
        ref_text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pcm_s16le", b"pcm_s16le", "ref_text", b"ref_text", "sample_rate", b"sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReferenceVoice: _TypeAlias = ReferenceVoice  # noqa: Y015

@_typing.final
class VoiceSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REFERENCE_VOICE_FIELD_NUMBER: _builtins.int
    PRESET_VOICE_ID_FIELD_NUMBER: _builtins.int
    preset_voice_id: _builtins.str
    @_builtins.property
    def reference_voice(self) -> Global___ReferenceVoice: ...
    def __init__(
        self,
        *,
        reference_voice: Global___ReferenceVoice | None = ...,
        preset_voice_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preset_voice_id", b"preset_voice_id", "reference_voice", b"reference_voice", "source", b"source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["preset_voice_id", b"preset_voice_id", "reference_voice", b"reference_voice", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_source: _TypeAlias = _typing.Literal["reference_voice", "preset_voice_id"]  # noqa: Y015
    _WhichOneofArgType_source: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_source) -> _WhichOneofReturnType_source | None: ...

Global___VoiceSource: _TypeAlias = VoiceSource  # noqa: Y015

@_typing.final
class SynthesizeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    DECODER_CHUNK_SIZE_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    language: _builtins.str
    decoder_chunk_size: _builtins.int
    @_builtins.property
    def voice(self) -> Global___VoiceSource: ...
    def __init__(
        self,
        *,
        voice: Global___VoiceSource | None = ...,
        text: _builtins.str = ...,
        language: _builtins.str = ...,
        decoder_chunk_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["voice", b"voice"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["decoder_chunk_size", b"decoder_chunk_size", "language", b"language", "text", b"text", "voice", b"voice"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SynthesizeRequest: _TypeAlias = SynthesizeRequest  # noqa: Y015

@_typing.final
class DuplexStreamConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    DECODER_CHUNK_SIZE_FIELD_NUMBER: _builtins.int
    language: _builtins.str
    decoder_chunk_size: _builtins.int
    @_builtins.property
    def voice(self) -> Global___VoiceSource: ...
    def __init__(
        self,
        *,
        voice: Global___VoiceSource | None = ...,
        language: _builtins.str = ...,
        decoder_chunk_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["voice", b"voice"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["decoder_chunk_size", b"decoder_chunk_size", "language", b"language", "voice", b"voice"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DuplexStreamConfig: _TypeAlias = DuplexStreamConfig  # noqa: Y015

@_typing.final
class DuplexSynthesizeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    TEXT_CHUNK_FIELD_NUMBER: _builtins.int
    text_chunk: _builtins.str
    @_builtins.property
    def config(self) -> Global___DuplexStreamConfig: ...
    def __init__(
        self,
        *,
        config: Global___DuplexStreamConfig | None = ...,
        text_chunk: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "payload", b"payload", "text_chunk", b"text_chunk"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "payload", b"payload", "text_chunk", b"text_chunk"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["config", "text_chunk"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___DuplexSynthesizeRequest: _TypeAlias = DuplexSynthesizeRequest  # noqa: Y015

@_typing.final
class AudioChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PCM_S16LE_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    pcm_s16le: _builtins.bytes
    sample_rate: _builtins.int
    chunk_index: _builtins.int
    def __init__(
        self,
        *,
        pcm_s16le: _builtins.bytes = ...,
        sample_rate: _builtins.int = ...,
        chunk_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "pcm_s16le", b"pcm_s16le", "sample_rate", b"sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AudioChunk: _TypeAlias = AudioChunk  # noqa: Y015
