"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from nexus.protos.tts import tts_pb2 as _tts_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TtsServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TtsServiceAsyncStub: ...
    Synthesize: _grpc.UnaryStreamMultiCallable[_tts_pb2.SynthesizeRequest, _tts_pb2.AudioChunk]
    DuplexSynthesize: _grpc.StreamStreamMultiCallable[_tts_pb2.DuplexSynthesizeRequest, _tts_pb2.AudioChunk]

@_typing.type_check_only
class TtsServiceAsyncStub(TtsServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Synthesize: _aio.UnaryStreamMultiCallable[_tts_pb2.SynthesizeRequest, _tts_pb2.AudioChunk]  # type: ignore[assignment]
    DuplexSynthesize: _aio.StreamStreamMultiCallable[_tts_pb2.DuplexSynthesizeRequest, _tts_pb2.AudioChunk]  # type: ignore[assignment]

class TtsServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Synthesize(
        self,
        request: _tts_pb2.SynthesizeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_tts_pb2.AudioChunk], _abc.AsyncIterator[_tts_pb2.AudioChunk]]: ...

    @_abc_1.abstractmethod
    def DuplexSynthesize(
        self,
        request_iterator: _MaybeAsyncIterator[_tts_pb2.DuplexSynthesizeRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_tts_pb2.AudioChunk], _abc.AsyncIterator[_tts_pb2.AudioChunk]]: ...

def add_TtsServiceServicer_to_server(servicer: TtsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
