"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AudioEncoding:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AudioEncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RecognitionConfig._AudioEncoding.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUDIO_ENCODING_UNSPECIFIED: RecognitionConfig._AudioEncoding.ValueType  # 0
        """默认配置"""
        LINEAR16: RecognitionConfig._AudioEncoding.ValueType  # 1
        """16位有符号pcm (little-endian)"""

    class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper): ...
    AUDIO_ENCODING_UNSPECIFIED: RecognitionConfig.AudioEncoding.ValueType  # 0
    """默认配置"""
    LINEAR16: RecognitionConfig.AudioEncoding.ValueType  # 1
    """16位有符号pcm (little-endian)"""

    ENCODING_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: builtins.int
    LANGUAGE_CODE_FIELD_NUMBER: builtins.int
    ENABLE_AUTOMATIC_PUNCTUATION_FIELD_NUMBER: builtins.int
    HOTWORDS_FIELD_NUMBER: builtins.int
    HOTWORD_BIAS_FIELD_NUMBER: builtins.int
    encoding: Global___RecognitionConfig.AudioEncoding.ValueType
    sample_rate_hertz: builtins.int
    """采样率"""
    language_code: builtins.str
    enable_automatic_punctuation: builtins.bool
    """标点符号"""
    hotword_bias: builtins.float
    """热词偏置，用于调节热词识别概率（正值增强，负值削弱）"""
    @property
    def hotwords(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """热词列表，字符串数组格式， ["hey chatgpt", "openai"]"""

    def __init__(
        self,
        *,
        encoding: Global___RecognitionConfig.AudioEncoding.ValueType = ...,
        sample_rate_hertz: builtins.int = ...,
        language_code: builtins.str = ...,
        enable_automatic_punctuation: builtins.bool = ...,
        hotwords: collections.abc.Iterable[builtins.str] | None = ...,
        hotword_bias: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enable_automatic_punctuation", b"enable_automatic_punctuation", "encoding", b"encoding", "hotword_bias", b"hotword_bias", "hotwords", b"hotwords", "language_code", b"language_code", "sample_rate_hertz", b"sample_rate_hertz"]) -> None: ...

Global___RecognitionConfig: typing_extensions.TypeAlias = RecognitionConfig

@typing.final
class RecognizeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SpeechRecognitionResult]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[Global___SpeechRecognitionResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

Global___RecognizeResponse: typing_extensions.TypeAlias = RecognizeResponse

@typing.final
class SpeechRecognitionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALTERNATIVE_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    @property
    def alternative(self) -> Global___SpeechRecognitionAlternative: ...
    @property
    def start_time(self) -> google.protobuf.duration_pb2.Duration:
        """相对于音频开始的时间偏移"""

    @property
    def end_time(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        alternative: Global___SpeechRecognitionAlternative | None = ...,
        start_time: google.protobuf.duration_pb2.Duration | None = ...,
        end_time: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["alternative", b"alternative", "end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["alternative", b"alternative", "end_time", b"end_time", "start_time", b"start_time"]) -> None: ...

Global___SpeechRecognitionResult: typing_extensions.TypeAlias = SpeechRecognitionResult

@typing.final
class StreamingRecognizeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAMING_CONFIG_FIELD_NUMBER: builtins.int
    AUDIO_CONTENT_FIELD_NUMBER: builtins.int
    audio_content: builtins.bytes
    @property
    def streaming_config(self) -> Global___StreamingRecognitionConfig: ...
    def __init__(
        self,
        *,
        streaming_config: Global___StreamingRecognitionConfig | None = ...,
        audio_content: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["audio_content", b"audio_content", "streaming_config", b"streaming_config", "streaming_request", b"streaming_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio_content", b"audio_content", "streaming_config", b"streaming_config", "streaming_request", b"streaming_request"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["streaming_request", b"streaming_request"]) -> typing.Literal["streaming_config", "audio_content"] | None: ...

Global___StreamingRecognizeRequest: typing_extensions.TypeAlias = StreamingRecognizeRequest

@typing.final
class StreamingRecognitionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    INTERIM_RESULTS_FIELD_NUMBER: builtins.int
    interim_results: builtins.bool
    """是否返回临时结果"""
    @property
    def config(self) -> Global___RecognitionConfig: ...
    def __init__(
        self,
        *,
        config: Global___RecognitionConfig | None = ...,
        interim_results: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "interim_results", b"interim_results"]) -> None: ...

Global___StreamingRecognitionConfig: typing_extensions.TypeAlias = StreamingRecognitionConfig

@typing.final
class StreamingRecognizeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___StreamingRecognitionResult]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[Global___StreamingRecognitionResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

Global___StreamingRecognizeResponse: typing_extensions.TypeAlias = StreamingRecognizeResponse

@typing.final
class StreamingRecognitionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALTERNATIVE_FIELD_NUMBER: builtins.int
    IS_FINAL_FIELD_NUMBER: builtins.int
    is_final: builtins.bool
    @property
    def alternative(self) -> Global___SpeechRecognitionAlternative: ...
    def __init__(
        self,
        *,
        alternative: Global___SpeechRecognitionAlternative | None = ...,
        is_final: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["alternative", b"alternative"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["alternative", b"alternative", "is_final", b"is_final"]) -> None: ...

Global___StreamingRecognitionResult: typing_extensions.TypeAlias = StreamingRecognitionResult

@typing.final
class SpeechRecognitionAlternative(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSCRIPT_FIELD_NUMBER: builtins.int
    WORDS_FIELD_NUMBER: builtins.int
    transcript: builtins.str
    @property
    def words(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___WordInfo]: ...
    def __init__(
        self,
        *,
        transcript: builtins.str = ...,
        words: collections.abc.Iterable[Global___WordInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["transcript", b"transcript", "words", b"words"]) -> None: ...

Global___SpeechRecognitionAlternative: typing_extensions.TypeAlias = SpeechRecognitionAlternative

@typing.final
class WordInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORD_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    word: builtins.str
    @property
    def start_time(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def end_time(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        word: builtins.str = ...,
        start_time: google.protobuf.duration_pb2.Duration | None = ...,
        end_time: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time", "word", b"word"]) -> None: ...

Global___WordInfo: typing_extensions.TypeAlias = WordInfo
